<?xml version="1.0" encoding="UTF-8"?>
<v804_stream>
    <session>
        <packet_size>1024</packet_size>
        <packet_recv/>
        <packet_sent/>
        <packet_send_drop/>
        <packet_recv_drop/>
        <tscount/>
        <intr_status/>
        <overflow/>
        <underflow/>
        <tx_overflow/>
        <tx_underflow/>
        <tx_count/>
        <waitfailed/>
        <dma_timeout/>
        <fpga_test/>
    </session>
    <session>
        <packet_size>1024</packet_size>
        <packet_recv/>
        <packet_sent/>
        <packet_send_drop/>
        <packet_recv_drop/>
        <tscount/>
        <intr_status/>
        <overflow/>
        <underflow/>
        <tx_overflow/>
        <tx_underflow/>
        <tx_count/>
        <waitfailed/>
        <dma_timeout/>
        <fpga_test/>
    </session>
    <session>
        <packet_size>1024</packet_size>
        <packet_recv/>
        <packet_sent/>
        <packet_send_drop/>
        <packet_recv_drop/>
        <tscount/>
        <intr_status/>
        <overflow/>
        <underflow/>
        <tx_overflow/>
        <tx_underflow/>
        <tx_count/>
        <waitfailed/>
        <dma_timeout/>
        <fpga_test/>
    </session>
    <session>
        <packet_size>1024</packet_size>
        <packet_recv/>
        <packet_sent/>
        <packet_send_drop/>
        <packet_recv_drop/>
        <tscount/>
        <intr_status/>
        <overflow/>
        <underflow/>
        <tx_overflow/>
        <tx_underflow/>
        <tx_count/>
        <waitfailed/>
        <dma_timeout/>
        <fpga_test/>
    </session>
    <timerid>1</timerid>
    <packet_size>256</packet_size>
    <irq_threshold>8192</irq_threshold>
    <rate_info/>
    <tx_rate>128</tx_rate>
    <task>
          <sched>
            <policy>fifo</policy>
            <priority>99</priority>
          </sched>
        <stream>
          <s>
            <id>1000</id>
            <mode>write</mode>
            <bs>1024000</bs>
          </s>
          <s>
            <id>1001</id>
            <mode>read</mode>
            <bs>1024000</bs>
            <overwrite/>
          </s>
          <s>
            <id>1010</id>
            <mode>write</mode>
            <bs>1024000</bs>
          </s>
          <s>
            <id>1011</id>
            <mode>read</mode>
            <bs>1024000</bs>
            <overwrite/>
          </s>
          <s>
            <id>1020</id>
            <mode>write</mode>
            <bs>1024000</bs>
          </s>
          <s>
            <id>1021</id>
            <mode>read</mode>
            <bs>1024000</bs>
            <overwrite/>
          </s>
          <s>
            <id>1030</id>
            <mode>write</mode>
            <bs>1024000</bs>
          </s>
          <s>
            <id>1031</id>
            <mode>read</mode>
            <bs>1024000</bs>
            <overwrite/>
          </s>
        </stream>
    </task>
</v804_stream>
